"""Recommendation workflow budgets and output limits."""

from __future__ import annotations

SEARCH_RESULTS_PER_QUERY = 20
MAX_UNIQUE_CANDIDATES = 40
MAX_DEEP_INSPECTION = 12
MAX_CONCURRENT_INSPECTIONS = 4
MAX_VARIANT_DEEP_INSPECTION = 6

MAX_RECOMMENDATIONS = 5
MAX_ALTERNATIVES = MAX_RECOMMENDATIONS - 1


__all__ = [
    "MAX_ALTERNATIVES",
    "MAX_CONCURRENT_INSPECTIONS",
    "MAX_DEEP_INSPECTION",
    "MAX_RECOMMENDATIONS",
    "MAX_UNIQUE_CANDIDATES",
    "MAX_VARIANT_DEEP_INSPECTION",
    "SEARCH_RESULTS_PER_QUERY",
]
